package com.xiaozhen.mall.tiny.mbg.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_brand
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PmsBrand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   首字母
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.first_letter
     *
     * @mbggenerated
     */
    private String firstLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   是否为品牌制造商：0->不是；1->是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.factory_status
     *
     * @mbggenerated
     */
    private Integer factoryStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.show_status
     *
     * @mbggenerated
     */
    private Integer showStatus;

    /**
     * Database Column Remarks:
     *   产品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.product_count
     *
     * @mbggenerated
     */
    private Integer productCount;

    /**
     * Database Column Remarks:
     *   产品评论数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.product_comment_count
     *
     * @mbggenerated
     */
    private Integer productCommentCount;

    /**
     * Database Column Remarks:
     *   品牌logo
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * Database Column Remarks:
     *   专区大图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.big_pic
     *
     * @mbggenerated
     */
    private String bigPic;

    /**
     * Database Column Remarks:
     *   品牌故事
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.brand_story
     *
     * @mbggenerated
     */
    private String brandStory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_brand
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.id
     *
     * @return the value of pms_brand.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.id
     *
     * @param id the value for pms_brand.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.name
     *
     * @return the value of pms_brand.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.name
     *
     * @param name the value for pms_brand.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.first_letter
     *
     * @return the value of pms_brand.first_letter
     *
     * @mbggenerated
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.first_letter
     *
     * @param firstLetter the value for pms_brand.first_letter
     *
     * @mbggenerated
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.sort
     *
     * @return the value of pms_brand.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.sort
     *
     * @param sort the value for pms_brand.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.factory_status
     *
     * @return the value of pms_brand.factory_status
     *
     * @mbggenerated
     */
    public Integer getFactoryStatus() {
        return factoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.factory_status
     *
     * @param factoryStatus the value for pms_brand.factory_status
     *
     * @mbggenerated
     */
    public void setFactoryStatus(Integer factoryStatus) {
        this.factoryStatus = factoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.show_status
     *
     * @return the value of pms_brand.show_status
     *
     * @mbggenerated
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.show_status
     *
     * @param showStatus the value for pms_brand.show_status
     *
     * @mbggenerated
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.product_count
     *
     * @return the value of pms_brand.product_count
     *
     * @mbggenerated
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.product_count
     *
     * @param productCount the value for pms_brand.product_count
     *
     * @mbggenerated
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.product_comment_count
     *
     * @return the value of pms_brand.product_comment_count
     *
     * @mbggenerated
     */
    public Integer getProductCommentCount() {
        return productCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.product_comment_count
     *
     * @param productCommentCount the value for pms_brand.product_comment_count
     *
     * @mbggenerated
     */
    public void setProductCommentCount(Integer productCommentCount) {
        this.productCommentCount = productCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.logo
     *
     * @return the value of pms_brand.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.logo
     *
     * @param logo the value for pms_brand.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.big_pic
     *
     * @return the value of pms_brand.big_pic
     *
     * @mbggenerated
     */
    public String getBigPic() {
        return bigPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.big_pic
     *
     * @param bigPic the value for pms_brand.big_pic
     *
     * @mbggenerated
     */
    public void setBigPic(String bigPic) {
        this.bigPic = bigPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.brand_story
     *
     * @return the value of pms_brand.brand_story
     *
     * @mbggenerated
     */
    public String getBrandStory() {
        return brandStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.brand_story
     *
     * @param brandStory the value for pms_brand.brand_story
     *
     * @mbggenerated
     */
    public void setBrandStory(String brandStory) {
        this.brandStory = brandStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", firstLetter=").append(firstLetter);
        sb.append(", sort=").append(sort);
        sb.append(", factoryStatus=").append(factoryStatus);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", productCount=").append(productCount);
        sb.append(", productCommentCount=").append(productCommentCount);
        sb.append(", logo=").append(logo);
        sb.append(", bigPic=").append(bigPic);
        sb.append(", brandStory=").append(brandStory);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}