package com.xiaozhen.mall.tiny.mbg.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_comment
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PmsComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.member_nick_name
     *
     * @mbggenerated
     */
    private String memberNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   评价星数：0->5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.star
     *
     * @mbggenerated
     */
    private Integer star;

    /**
     * Database Column Remarks:
     *   评价的ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.member_ip
     *
     * @mbggenerated
     */
    private String memberIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.show_status
     *
     * @mbggenerated
     */
    private Integer showStatus;

    /**
     * Database Column Remarks:
     *   购买时的商品属性
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.product_attribute
     *
     * @mbggenerated
     */
    private String productAttribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.collect_couont
     *
     * @mbggenerated
     */
    private Integer collectCouont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.read_count
     *
     * @mbggenerated
     */
    private Integer readCount;

    /**
     * Database Column Remarks:
     *   上传图片地址，以逗号隔开
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.pics
     *
     * @mbggenerated
     */
    private String pics;

    /**
     * Database Column Remarks:
     *   评论用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.member_icon
     *
     * @mbggenerated
     */
    private String memberIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.replay_count
     *
     * @mbggenerated
     */
    private Integer replayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.id
     *
     * @return the value of pms_comment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.id
     *
     * @param id the value for pms_comment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.product_id
     *
     * @return the value of pms_comment.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.product_id
     *
     * @param productId the value for pms_comment.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.member_nick_name
     *
     * @return the value of pms_comment.member_nick_name
     *
     * @mbggenerated
     */
    public String getMemberNickName() {
        return memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.member_nick_name
     *
     * @param memberNickName the value for pms_comment.member_nick_name
     *
     * @mbggenerated
     */
    public void setMemberNickName(String memberNickName) {
        this.memberNickName = memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.product_name
     *
     * @return the value of pms_comment.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.product_name
     *
     * @param productName the value for pms_comment.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.star
     *
     * @return the value of pms_comment.star
     *
     * @mbggenerated
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.star
     *
     * @param star the value for pms_comment.star
     *
     * @mbggenerated
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.member_ip
     *
     * @return the value of pms_comment.member_ip
     *
     * @mbggenerated
     */
    public String getMemberIp() {
        return memberIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.member_ip
     *
     * @param memberIp the value for pms_comment.member_ip
     *
     * @mbggenerated
     */
    public void setMemberIp(String memberIp) {
        this.memberIp = memberIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.create_time
     *
     * @return the value of pms_comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.create_time
     *
     * @param createTime the value for pms_comment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.show_status
     *
     * @return the value of pms_comment.show_status
     *
     * @mbggenerated
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.show_status
     *
     * @param showStatus the value for pms_comment.show_status
     *
     * @mbggenerated
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.product_attribute
     *
     * @return the value of pms_comment.product_attribute
     *
     * @mbggenerated
     */
    public String getProductAttribute() {
        return productAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.product_attribute
     *
     * @param productAttribute the value for pms_comment.product_attribute
     *
     * @mbggenerated
     */
    public void setProductAttribute(String productAttribute) {
        this.productAttribute = productAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.collect_couont
     *
     * @return the value of pms_comment.collect_couont
     *
     * @mbggenerated
     */
    public Integer getCollectCouont() {
        return collectCouont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.collect_couont
     *
     * @param collectCouont the value for pms_comment.collect_couont
     *
     * @mbggenerated
     */
    public void setCollectCouont(Integer collectCouont) {
        this.collectCouont = collectCouont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.read_count
     *
     * @return the value of pms_comment.read_count
     *
     * @mbggenerated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.read_count
     *
     * @param readCount the value for pms_comment.read_count
     *
     * @mbggenerated
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.pics
     *
     * @return the value of pms_comment.pics
     *
     * @mbggenerated
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.pics
     *
     * @param pics the value for pms_comment.pics
     *
     * @mbggenerated
     */
    public void setPics(String pics) {
        this.pics = pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.member_icon
     *
     * @return the value of pms_comment.member_icon
     *
     * @mbggenerated
     */
    public String getMemberIcon() {
        return memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.member_icon
     *
     * @param memberIcon the value for pms_comment.member_icon
     *
     * @mbggenerated
     */
    public void setMemberIcon(String memberIcon) {
        this.memberIcon = memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.replay_count
     *
     * @return the value of pms_comment.replay_count
     *
     * @mbggenerated
     */
    public Integer getReplayCount() {
        return replayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.replay_count
     *
     * @param replayCount the value for pms_comment.replay_count
     *
     * @mbggenerated
     */
    public void setReplayCount(Integer replayCount) {
        this.replayCount = replayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.content
     *
     * @return the value of pms_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.content
     *
     * @param content the value for pms_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", memberNickName=").append(memberNickName);
        sb.append(", productName=").append(productName);
        sb.append(", star=").append(star);
        sb.append(", memberIp=").append(memberIp);
        sb.append(", createTime=").append(createTime);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", productAttribute=").append(productAttribute);
        sb.append(", collectCouont=").append(collectCouont);
        sb.append(", readCount=").append(readCount);
        sb.append(", pics=").append(pics);
        sb.append(", memberIcon=").append(memberIcon);
        sb.append(", replayCount=").append(replayCount);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}