package com.xiaozhen.mall.tiny.mbg.mapper;

import com.xiaozhen.mall.tiny.mbg.model.PmsAlbum;
import com.xiaozhen.mall.tiny.mbg.model.PmsAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int countByExample(PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int deleteByExample(PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int insert(PmsAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int insertSelective(PmsAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    List<PmsAlbum> selectByExample(PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    PmsAlbum selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PmsAlbum record, @Param("example") PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PmsAlbum record, @Param("example") PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PmsAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmsAlbum record);
}